apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-argo
  namespace: argo-test-ns
spec:
  selector:
    matchLabels:
      run: my-nginx-argo
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx-argo
    spec:
      containers:
      - name: my-nginx-argo
        image: nginx
        ports:
        - containerPort: 80
