apiVersion: v1
kind: Service
metadata:
  name: my-nginx-argo-svc
  namespace: argo-test-ns
  labels:
    run: my-nginx-argo
spec:
  ports:
  - port: 80
    protocol: TCP
  type: NodePort
  selector:
    run: my-nginx-argo
